# <center> Programació numèrica

## __**Excercici 1**__

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. 
Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [36]:
import numpy as np
import pandas as pd

In [37]:
def resum_estadistic(arr):
    data = pd.Series([x])
    if arr.ndim != 1:
        raise Exception("ha de ser unidimensional")
    else:
        print(data.describe())
if __name__ == "__main__":
        x = np.random.randint(0,10,5)
        resum_estadistic(x)
        

count                   1
unique                  1
top       [2, 3, 3, 1, 0]
freq                    1
dtype: object


## __**Excercici 2**__

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100

In [38]:
def square():
    y = np.random.randint(2,5)
    matrix = np.random.randint(0,100,(y,y))
    print(matrix)
if __name__ == "__main__":
    square()

[[99 40 60 92]
 [52 97  2 30]
 [69 73 72 41]
 [96 71 91 43]]


## __**Excercici 3**__

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [39]:
def total(df):

    sum_colums =df.sum(axis=0)
    sum_rows = df.sum(axis= 1)
    print(df)
    print(sum_colums)
    print(sum_rows)
if __name__ == "__main__":
    df = pd.DataFrame(np.random.randint(0, 100, size=(5, 5)), columns=list('ABCDE'))
    total(df)

    A   B   C   D   E
0  14  56  99  35   4
1   3  86  92  69  72
2   3   9  36  26  98
3  86  59  60  27  24
4  82   2  34   5  41
A    188
B    212
C    321
D    162
E    239
dtype: int64
0    208
1    322
2    172
3    256
4    164
dtype: int64


## __**Excercici 4**__

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [40]:
def coeficient_correlacio():
    data = pd.DataFrame(np.random.randint(0, 100, size=(10, 2)), columns=list('XY'))
    product_x_y = pd.Series([],dtype='float64')
    power_x =pd.Series([],dtype='float64')
    power_y = pd.Series([],dtype='float64')
    
    for index,row  in data.iterrows():

        c = row[0]*row[1]
        product_x_y[index]= c
        power_x[index]=row[0]**2
        power_y[index] = row[1]**2

    data.insert(2,'X*Y',product_x_y)
    data.insert(2,'X^2',power_x)
    data.insert(2, 'Y^2', power_y)

    print(data)
   
    mitja_x = data['X'].sum()/len(data)
    mitja_y = data['Y'].sum() / len(data)
    print("\nMitja de X:", mitja_x)
    print("Mitja de Y:",mitja_y)
    
    

    mitja_product_x_y = data['X*Y'].sum() /len(data)
    covariança = mitja_product_x_y - (mitja_x * mitja_y)
    print("Mitja del producte de X i Y:",mitja_product_x_y)
    print("Producte de la mitja de X i la mitja Y",mitja_x * mitja_y)
    print("Covariança", covariança)
    desviacio_tipica_x =np.sqrt((data['X^2'].sum()/len(data))- (mitja_x **
                                                                2))
    desviacio_tipica_y = np.sqrt((data['Y^2'].sum() / len(data)) - (mitja_y ** 2))
    print("Desviació_tipica de X:",desviacio_tipica_x)
    print("Desviació_tipica de Y:",desviacio_tipica_y)
    coef_correlacio = (covariança)/(desviacio_tipica_x  * desviacio_tipica_y)
    print("Coeficient de correlació:",coef_correlacio)
    
if __name__ == "__main__":
    coeficient_correlacio()

    X   Y   Y^2   X^2   X*Y
0  55  52  2704  3025  2860
1  25  76  5776   625  1900
2  55   2     4  3025   110
3  95  24   576  9025  2280
4  15  73  5329   225  1095
5  56  18   324  3136  1008
6  99   2     4  9801   198
7  28  79  6241   784  2212
8   6  54  2916    36   324
9  68  32  1024  4624  2176

Mitja de X: 50.2
Mitja de Y: 41.2
Mitja del producte de X i Y: 1416.3
Producte de la mitja de X i la mitja Y 2068.2400000000002
Covariança -651.9400000000003
Desviació_tipica de X: 30.175486740067665
Desviació_tipica de Y: 28.14888985377576
Coeficient de correlació: -0.7675241906368655
